### ISSUE TITLE
demo.sid.ai Google Drive results incorrect

### ISSUE THREAD

**Issue by alexandrereol** [sidhq/SID#6]
Hi there SID team,
the Google Drive integration seems to return valid data/response in the API request, but not in the web interface of demo.sid.ai. Correct data from my Google Drive appears behind the red rectangle of the screenshot, but not in the chat interface

![CleanShot 2023-07-16 at 21 45 05@2x](https://github.com/sidhq/SID/assets/81623991/fc859632-d5bc-4281-93f7-bef4f91a9ff5)

**Comment by gvilums** [comment]
This is more of a limitation of the current search system than an incorrect result. The problem is that the data returned by the api, while containing text snippets from your google drive files, does not _directly_ answer the question "what is the last file I worked on".

In general, the best-supported queries are those which address the _content_ of your gdrive/notion/etc., not the state of the files themselves.

**Comment by alexandrereol** [comment]
I see. I'd suggest you modify the chat response to not say "_i'm an AI assistant and don't have access to your data_" but rather something explaining that this kind of question about metadata is not (yet?) supported :)

**Comment by ruflair** [comment]
We will iterate on the system prompt for the assistant, for now we have switched from gpt-3.5-turbo to gpt-4 to improve results, thank you for the suggestion!
